HOMEWORK 1

In [3]:
# Dependencies

import pandas as pd
import numpy as np

Getting the data

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q1. Pandas version

In [5]:
pd.__version__

'2.2.3'

Q2. Records count

In [6]:
len(df)

10000

Q3. Fuel types

In [7]:
df['fuel_type'].unique() # There are three types of fuel

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

Q4. Missing values

In [8]:
df.isnull().sum() # There are two columns with missing values

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5. Max fuel efficiency

In [9]:
df['fuel_efficiency_mpg'].max()

41.2

Q6. Median value of horsepower

In [10]:
df['horsepower'].median() # Median of the variable Horsepower

254.0

In [11]:
df['horsepower'].mode() # Most frequent value

0    252.0
Name: horsepower, dtype: float64

In [12]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

In [13]:
df['horsepower'].median() # New median after fillna

254.0

Q7. Sum of weights

In [14]:
df_asia = df[df['origin'] == 'Asia'] # Only Asian cars

X = df_asia[['vehicle_weight', 'model_year']].head(7).to_numpy()
# Selected variables, first 7 observations, creating a np array

XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = XTX_inv.dot(X.T).dot(y)

print(w.sum()) # Sum of all the elements of the result

0.36919696904925486